#ifndef PICTUREREADER_GLOBAL_H
#define PICTUREREADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PICTUREREADER_LIBRARY)
#  define PICTUREREADER_EXPORT Q_DECL_EXPORT
#else
#  define PICTUREREADER_EXPORT Q_DECL_IMPORT
#endif

#endif // PICTUREREADER_GLOBAL_H
